### ISSUE TITLE
Next Meetup -  #2

### ISSUE THREAD

**Issue by franzejr** [knowbody/react-native-online-meetups#34]
This is the issue to talk about the next meetup. 🙌 

Ideas for topics, check the [suggested topics](https://github.com/knowbody/react-native-online-meetups/blob/master/suggestedTopics.md).

*Date/Time:* TBD

*Speakers:*
- @axemclion
-  @sanketsahusoft
- @peterpme 

If you want to be a speaker in the next meetup, comment on this issue!

We will have 3 speakers on this meetup. Each talk during 20 ~ 30 min (including questions).

**Comment by franzejr** [comment]
@kelset @knowbody, do you guys think 3 speakers (20 ~ 30min per speaker) was ok in the last meetup? Do you think we can stick with this standard? We can always change ;)

**Comment by knowbody** [comment]
I only jumped in in the very end of it, I'm going to rewatch it today or tomorrow and will get back to you.

**Comment by designorant** [comment]
May I suggest using Google Hangouts instead of BigMarker? Hangouts seem to have better resolution/sharpness, and the sound seems much sharper (although I understand there are many factors contributing to that). The size of the shared screens is also bigger, therefore easier to follow along.

A dedicated channel on YouTube (#1) would also be much more useful than a generic one.

**Comment by knowbody** [comment]
@franzejr I think 3 speakers seems to be a good number for ~1hr long meetup.

@designorant I don't mind the platform whatever works best in terms of the setting for speakers and the audience, I quite like the chat and the QA being built-in to BigMarker, but the same can be achieved via comments on YouTube. If the quality is an issue maybe better to use Hangouts (cc: @franzejr)? or maybe that could be fixed on BigMaker?
also if we use BigMaker is it still possible to upload the recording to YouTube?

**Comment by franzejr** [comment]
About the number of speakers, it's cool then! @knowbody 

Related to the Bigmarker I'm checking with the Bigmarker about this, but it's possible to upload to youtube, as I did in the last one! I really liked the Q&A / chat tha bigmarker provides and the hability to share mic with attendees (with we want to ). Let's check if we can improve the quality with Bigmarker! I keep you guys posted!

**Comment by sanketsahu** [comment]
@franzejr Can I speak again on a different topic?

**Comment by franzejr** [comment]
For sure @sanketsahusoft ;-), but let's try to get more speakers!

**Comment by kelset** [comment]
So:

1. The number of speakers

Yeah I think that 3 is the best number. There are ~12 people in the speakers .md, and a lot of them never spoke. It would be cool to have some "fresh blood" each session if possible (imho).

2. Platform

I don't mind too much having BigMarker as a platform: the main issues we faced last time I think were caused by settings changing during live (at least that was my impression watching it, @franzejr  were u trying to modify something?). Maybe we can keep it for next meetup, and if we still have a lot of issues we can move back to Hangouts.

3. Dedicated YouTube Channel

I agree with @designorant over the fact that right now the vids are scattered, a dedicated channel would be ideal. A playlist could serve as a surrogate.

4. Format

During the last meetup, I liked @dabit3 segment because it was more "practical", in a strict sense. I think that it would be nice to have at least 1 out of 3 speakers do some"coding" session, to keep it more "friendly".
I know it may sound far-fetched: I like having people like @GantMan and @sanketsahusoft present something cool like they did last time, but at the same time React Native is about coding with something "yet to be fully explored".

So I'd love to have more "hacks & tricks" sessions; that way I think a lot more people could join the speakers' lineup (heck, I'm considering it) without having to worry too much to create slideshows.

**Comment by franzejr** [comment]
Playlist: https://www.youtube.com/playlist?list=PLeonCbPZMjh1UCtEeFOcUM68OkpyJsc6O using the Remote Meetup channel.

**Comment by kelset** [comment]
@franzejr can you add the #0 to it? https://www.youtube.com/watch?v=6dek2apWWZA

**Comment by franzejr** [comment]
Yes! @kelset ! I will do that later tonight!

**Comment by peterpme** [comment]
:wave: I'd be happy to jump on the next one!

For reference: Timezone CST and I'm usually free throughout the day!

My favorite talking points about React Native (similar to Nader's and Gant's):

- Practical ways of moving quickly while still retaining code quality
  - I'm involved in startups. Scarce resources means we have to move quickly. I *hate* writing spaghetti code, even if its throw-away. I've gotten very good at balancing between the two.
  - I can put together a scalable app quickly and efficiently and only refactor small parts when needed
- Build Tools / Environment / Workflows
  - Before I could call myself a *programmer*, I spent a lot of times playing with Terminal. Ever since then, config files, dev environments, workflows, etc have been a small passion of mine. I like automation and moving quickly
  - Simple workflows that evolve over time:
     - Using Alfred: "find app-release.apk" find apk easily so I can upload it
     - Wrapping `./assembleRelease` to open app-release.apk, open Android Dev console in Chrome so I don't have to type it in every time
     - Automating the upload process for myself (TBD)
     - Generating app icons using off the shelf tooling, etc

The list goes on, but hopefully it gives you an idea :)

**Comment by franzejr** [comment]
Thanks, @peterpme ! You can chose any of these you want! I'm going and add you to the list and then we need to find a good date/time to everyone! It's really cool!

**Comment by kelset** [comment]
Now that we have the lineup we should start thinking about the time/date: second half of March?

**Comment by peterpme** [comment]
How about the last week of March? 27-31?

I will be out of town for my birthday, March 22 :)

**Comment by franzejr** [comment]
Sorry the late reply! If everyone agrees, we can do that March 31 ?
I have [created the event](https://www.bigmarker.com/remote-meetup/React-Native-Remote-Meetup-2), but we can still change the date/time. 

I will get in touch with @axemclion @sanketsahusoft @peterpme to get each e-mail and send the invite as speakers.

@kelset, wanna help me as a host too?

**Comment by sanketsahu** [comment]
@franzejr I am not available on March 31st. Can we do it a week after that? If not, I will let other speakers carry on.

**Comment by kelset** [comment]
Today I'll move to London, so I can't be sure of being able to attend right now, first I need a couple days to settle down and get the rhythm of the new routine ;)

Of course the "priority" is that the speakers can attend, no issue for me in pushing it a week further.

Obviously if I can partecipate I'll be glad to help out!

(btw I just noticed that the readme is not being formatted properly, did they change the markdown format?)

**Comment by franzejr** [comment]
@axemclion and @peterpme, can you do one week later?

**Comment by peterpme** [comment]
We can do a week later :)

**Comment by franzejr** [comment]
What about April 07? @axemclion @sanketsahusof @peterpme

**Comment by axemclion** [comment]
@franzejr April 07 works for me. What time ?

**Comment by franzejr** [comment]
Same time as the others: 6PM GMT. Is this ok to everyone ? @axemclion @sanketsahusoft  @peterpme?

April 07, 06 PM GMT.

**Comment by sanketsahu** [comment]
@franzejr Works for me! I can talk about MobX vs Redux. I presented that at a local React meetup.

**Comment by franzejr** [comment]
Nice @sanketsahusoft !

**Comment by gergob** [comment]
hi @franzejr will there be a calendar invite or so for the next meetup ? Thanks!

**Comment by peterpme** [comment]
6pm GMT (1pm CST in Chicago) works for me!

**Comment by franzejr** [comment]
nice @peterpme !

@gergob, here: https://www.bigmarker.com/remote-meetup/React-Native-Remote-Meetup-2/

**Comment by axemclion** [comment]
The time works for me too.

**Comment by franzejr** [comment]
Ok! It seems we have a date and time!

**React Native Remote Meetup  w/ @sanketsahu @nparashuram and @peterpme - April 7, 6PM GMT. Get your spot today! at  http://buff.ly/2nJgjER** 

RT are welcome: https://twitter.com/RemoteMeetup/status/846786727020810240

**Comment by franzejr** [comment]
I'm closing this issue, if you want to talk in the Next Remote Meetup, check out https://github.com/knowbody/react-native-online-meetups/issues/38.
